# Generated by Django 5.1.2 on 2026-07-15 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_productimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier who uploaded this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
