# Generated by Django 5.1.2 on 2026-07-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo video URL'),
        ),
    ]
