# Generated by Django 5.1.2 on 2026-07-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price (leave empty for no sale)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='angle',
            field=models.CharField(blank=True, choices=[('front', 'Front'), ('back', 'Back'), ('left', 'Left Side'), ('right', 'Right Side'), ('top', 'Top'), ('bottom', 'Bottom'), ('detail', 'Detail Close-up'), ('lifestyle', 'Lifestyle / In Use'), ('packaging', 'Packaging')], default='front', max_length=20),
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.CharField(blank=True, choices=[('', 'No Color'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('black', 'Black'), ('white', 'White'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('pink', 'Pink'), ('orange', 'Orange'), ('gray', 'Gray'), ('brown', 'Brown'), ('silver', 'Silver'), ('gold', 'Gold')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='productimage',
            name='label',
            field=models.CharField(blank=True, help_text="Optional label like 'Midnight Blue', 'Matte Finish'", max_length=100),
        ),
        migrations.AddField(
            model_name='productimage',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
    ]
