# Generated by Django 5.1.2 on 2026-07-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_productimage_options_product_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_3d',
            field=models.FileField(blank=True, help_text='3D model file (.glb, .gltf) for AR/VR viewing', null=True, upload_to='products/3d/'),
        ),
    ]
