# Generated by Django 5.1.2 on 2026-07-21 18:31

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_model_3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='categories/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/gallery/', validators=[core.validators.validate_image_file]),
        ),
    ]
