# Generated by Django 5.1.2 on 2026-07-23 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_newslettersubscriber_blogpost_collection_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Hide product from shop (for duplicate/archive management)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Unique SKU for inventory tracking', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for organization', max_length=500),
        ),
        migrations.CreateModel(
            name='ProductRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(max_length=180, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('new_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects_from', to='core.product')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Blue / XL' or 'Red / M'", max_length=100)),
                ('sku', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty to use parent price', max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.product')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
    ]
