# Generated by Django 5.1.2 on 2026-07-23 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_archived_at_product_is_archived_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='size',
            field=models.ForeignKey(blank=True, help_text='Link image to a specific size (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='core.productsize'),
        ),
    ]
