# Generated by Django 5.1.2 on 2026-07-17 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_productimage_options_product_sale_price_and_more'),
        ('dashboard', '0003_loyaltypoint_sharelink_useractivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Eid Special Offer', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. 30% OFF on all products', max_length=300)),
                ('discount_text', models.CharField(blank=True, help_text='e.g. 30% OFF', max_length=50)),
                ('bg_color', models.CharField(default='#4f46e5', help_text='Background color hex code', max_length=30)),
                ('text_color', models.CharField(default='#ffffff', help_text='Text color hex code', max_length=30)),
                ('button_text', models.CharField(blank=True, help_text='e.g. Shop Now', max_length=50)),
                ('button_url', models.CharField(blank=True, help_text='e.g. /products/ or /products/slug/', max_length=300)),
                ('position', models.CharField(choices=[('hero_left', 'Hero Left'), ('hero_right', 'Hero Right'), ('below_hero', 'Below Hero')], default='hero_left', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, help_text='Featured product to show', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
            ],
            options={
                'ordering': ['order', '-created'],
            },
        ),
    ]
