# Generated by Django 5.1.2 on 2026-07-21 18:31

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_purchaseorder_purchaseorderitem_supplierprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='banners/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='site/', validators=[core.validators.validate_image_file]),
        ),
    ]
